name: Push To Yandex Cloud CR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpp5qmt2u1jr41cma29
          CR_REPOSITORY: tower-defense
          IMAGE_TAG: ${{ github.sha }}
          CLIENT_PORT: 3000
          SERVER_PORT: 3001
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432

        run: |
          docker compose build
          docker tag prakticum-client-1:latest cr.yandex/$CR_REGISTRY/prakticum-client-1:latest
          docker push cr.yandex/$CR_REGISTRY/prakticum-client-1:latest
          docker tag prackicum-server-2:latest cr.yandex/$CR_REGISTRY/prackicum-server-2:latest
          docker push cr.yandex/$CR_REGISTRY/prackicum-server-2:latest
          docker tag postgres:14 cr.yandex/$CR_REGISTRY/postgres:14
          docker push cr.yandex/$CR_REGISTRY/postgres:14
